os:
- linux
- osx

env:
  global:
  - secure: jrAuM2d8/Pu83cps6cIzoZl/uOcz3cd53Sb/16kWujrb03dKFn+avOSRapOqU9eYMRIMi75fYsKc0rK4UHGRoCBmYLMHVZdZJvlcVxLqIF/+CQjwvYCezyoRLW5POIuTcJr/jGOuoilYQgx56Dv97ZIndeczZocAk3u2glcpT64=
  matrix:
  # Linux
  - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh
  - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-3.6.0-Linux-x86_64.sh
  # OS X
  - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda-3.6.0-MacOSX-x86_64.sh
  - MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-3.6.0-MacOSX-x86_64.sh

matrix:
  exclude:
  - os: linux
    env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda-3.6.0-MacOSX-x86_64.sh
  - os: linux
    env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-3.6.0-MacOSX-x86_64.sh
  - os: osx
    env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh
  - os: osx
    env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-3.6.0-Linux-x86_64.sh
  allow_failures:
  - env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-3.6.0-Linux-x86_64.sh
  - os: osx

install:
- export MENPO_VERSION=$(git describe --tags | sed 's/-/_/g' | cut -c2-)
- wget https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py -O
  traviconda.py
- chmod +x traviconda.py
- ./traviconda.py setup ./conda --url $MINICONDA_URL --channel menpo
- export PATH=/home/travis/miniconda/bin:$PATH

script:
- ./traviconda.py build ./conda --user menpo --key $BINSTAR_KEY

notifications:
  email: false
  flowdock: 769202b66114a5ce0e61df484dfeb177
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
