language: python
python:
  - 2.7
notifications:
  email: false
 
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python numpy scipy matplotlib mayavi scikit-image scikit-learn imaging cython nose
  - conda install --yes -c menpo cyrasterize cyassimp menpo-pyvrml97
  - pip install coveralls
  - python setup.py install --single-version-externally-managed --record=/tmp/record.txt
  - python setup.py build_ext --inplace
 
# Run test
script:
  - nosetests --with-coverage --cover-package=menpo menpo


# should be after_success, maybe change 
after_script:
  - coveralls
